// One field contract for existing borrower journeys. Empty estimates are valid.
module.exports = [
 ['loan_goal','What would you like to do?',['Not Sure Yet','Purchase','Refinance','Access equity','Invest','Build','Buy before selling']],
 ['income_type','What should I know about your situation?',['No special circumstance','Self-employed / business owner','Rental income','Substantial assets','Difficulty with another lender','Another circumstance','Not sure yet']],
 ['readiness','Where are you in the process?',['Exploring','Comparing options','Property identified','Under contract']],
 ['property_value','Approximate price or property value',null],
 ['target_city','City or area',null],
 ['down_payment','Estimated down payment',null,'Purchase|Invest|Build|Buy before selling'],
 ['current_balance','Current mortgage balance',null,'Refinance|Access equity|Buy before selling'],
 ['current_rate','Current interest rate (%)',null,'Refinance|Access equity'],
 ['refinance_goal','What would you like to change?',['Lower payment','Compare rate and costs','Change loan term','Use equity','Still deciding'],'Refinance|Access equity'],
 ['investment_action','What is the investment plan?',['Purchase','Refinance','Access equity','Still deciding'],'Invest'],
 ['property_type','Property type',['Single-family rental','Condo or townhome','2–4 units','5+ units / commercial','Not sure yet'],'Invest'],
 ['monthly_rent','Expected or current monthly rent',null,'Invest'],
 ['investment_strategy','Investment strategy',['Long-term rental','Short-term rental','Fix and flip','BRRRR / renovate and rent','Portfolio growth','Still deciding'],'Invest'],
 ['time_in_business','Time in business',['Less than 1 year','1–2 years','2 or more years','Not sure'],null,'Self-employed / business owner'],
 ['documentation_issue','Income or documentation question',null,null,'Self-employed / business owner|Substantial assets'],
 ['lender_status','Current loan stage',['Just started','Application submitted','Processing','Underwriting','Approved with conditions','Clear to close','Not sure'],null,'Difficulty with another lender'],
 ['closing_date','Closing date or deadline',null,null,'Difficulty with another lender'],
 ['switch_reason','Reason for considering a different lender',null,null,'Difficulty with another lender'],
 ['lot_status','Where are you with the lot?',['Still looking','Lot identified','Under contract','Already own the lot','Not sure'],'Build'],
 ['builder_status','Builder status',['Still comparing','Builder selected','Plans / bid in progress','Contract signed','Not sure'],'Build'],
 ['project_budget','Estimated total project budget',null,'Build'],
 ['build_timing','When would you like to start building?',null,'Build'],
 ['current_home_value','Approximate current-home value',null,'Buy before selling'],
 ['listing_status','Current-home status',['Not listed','Preparing to list','Listed for sale','Under contract','Sold'],'Buy before selling'],
 ['primary_constraint','What is the main constraint?',['Down payment tied up in equity','Qualifying with both payments','Avoiding two moves','Avoiding a sale contingency','Uncertain timing','Something else'],'Buy before selling'],
 ['timeline','Your timing or next milestone',null]
];
